apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: employee-service-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: employee-service

---

apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: employee-service-allow-reporting
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: employee-service

  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/{{ .Release.Namespace }}/sa/employee-sa"
      to:
        - operation:
             methods: ["GET"]
             paths: ["/employee/*"]


---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: employee-service-allow-ingress
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: employee-service

  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/ingress-nginx/sa/ingress-nginx"
      to:
        - operation:
            methods: ["GET"]
            paths: ["/employee/*"]