# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: employee-service-role
#   namespace: {{ .Release.Namespace }}
# rules:
#   - apiGroups: [""]
#     resources: ["configmaps"]
#     verbs: ["get", "list", "watch"]